name: Zig CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Zig 0.13.0
        uses: goto-bus-stop/setup-zig@v2
        with:
          zig-version: 0.13.0

      - name: Run unit tests
        run: zig build unit

      - name: Run full test suite
        run: zig build test
